### ISSUE TITLE
How about the API cost used in ranking model train stage?

### ISSUE THREAD

**Issue by A11en0** [ytyz1307zzh/Auto-Instruct#1]

**Comment by ytyz1307zzh** [comment]
Thanks for the question! The training data preparation consists of (1) instruction generation and (2) instruction labeling, and the cost mainly comes from the second step that finds out which instructions are better on the training examples.

Based on my memory, to label the instructions, we try every candidate instruction on up to 1k examples for each task. To expedite training, we only train on 8 candidate instructions for each example out of 22. Then we only keep those examples where not all instructions lead to the same ROUGE score (as mentioned in Appendix A), because we are using a list-wise ranking objective. You can also early-stop the labeling once enough "rankable" examples are collected for a single task.

In our training, we labeled all 22 candidate instructions and then did a balanced sampling of 8 instructions for training (we will release this part of code). But if the budget is tight, you can first sample instructions before labeling them. But anyway, the cost in tokens would be (num_instructions) x (num_train_examples) x (num_tasks) x (average_num_input_tokens). It is beneficial to choose tasks that are not too easy for LLMs. If it is too easy (especially some classification tasks), a lot of examples may be discarded since all instructions may be able to lead to a correct prediction.

**Comment by A11en0** [comment]
Fine, thanks for your reply! I think it is not a tiny API cost for search for a task, could you tell me what the total costs is?

**Comment by A11en0** [comment]
By the way, It seems lack of the codes for training the rank model.

**Comment by ytyz1307zzh** [comment]
Hi,

Thanks for the interest. The code is now uploaded.
