### ISSUE TITLE
Training Data for The Ranking FlanT5

### ISSUE THREAD

**Issue by PierreLepagnol** [ytyz1307zzh/Auto-Instruct#5]
Hello,

Thank you very much, and congratulations on your well-written code and paper.
I have a few questions regarding the training data of FlanT5:

1. As I understand it, you classified the tasks using the 'category' field in each 'task_metadata.json' file, found at 'data/niv2_english/TASK_NAME/task_metadata.json', resulting in 575 tasks for training. Is this correct?
2. For each task, you sampled 400 examples (pairs of candidate instructions, x, y, plus RougeL), following the filters outlined in Appendix A. You mentioned ending up with a total of 122K examples for training, but with 400 examples for each of the 575 tasks, this would amount to 230K total examples. Are there tasks with significantly fewer than 400 examples?

**Comment by ytyz1307zzh** [comment]
1. Yes, the 'category' field is what we used to split tasks into training and test sets. We made sure that training tasks and test tasks did not overlap in their category.
2. Some tasks had fewer than 400 training examples because not enough trainable examples were collected. Trainable examples mean different candidate instructions do not lead to the same result on that example.
